<?php
/**
 * This is the generated config.inc file
 *
 *
 * @package sdif2mysql
 */

$GLOBALS['config'] = Config::singleton();

$config->set('widget_image_path', '/images/widgets');
$config->set('file_cache_dir', '/var/www/html/flip-turn/webapps/sdif2mysql/cache');
$config->set('controller_request_debug', '1');
$config->set('cache_enabled', '1');
$config->set('uncaught_exception_trace_depth', '5');
$config->set('uncaught_exception_output', 'html');
$config->set('DB_TYPE', 'mysql');
$config->set('DB_HOST', 'localhost');
$config->set('DB_PORT', '3306');
$config->set('DB_NAME', 'sdif2mysql');
$config->set('DB_USERNAME', 'sdif2mysql');
$config->set('DB_PASSWORD', 'sdif2mysql');


?>